# Site settings
title: MinHye Joo
email: mjoo009@ucr.edu 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://MinHyeJoo.github.io/test/" # the base hostname & protocol for your site
github_username: MinHeyJoo
encoding: UTF-8
# Build settings
markdown: kramdown
